# Explore Code Predictor Generation Flow
import torch
from qwen_tts import Qwen3TTSModel

print("Loading model...")
model = Qwen3TTSModel.from_pretrained(
    "./model_0.6b",
    device_map="cpu",
    torch_dtype=torch.float32,
)
print("Model loaded!")

talker = model.model.talker
code_predictor = talker.code_predictor
cp_config = code_predictor.config

print("\n=== Understanding the Generation Flow ===")

# The Code Predictor predicts codebooks 1-15 from:
# 1. Hidden states from the main LM (for conditioning)
# 2. The first codebook tokens (generated by main LM)

batch_size = 1
seq_len = 10  # 10 codec tokens (from main LM)
hidden_dim = cp_config.hidden_size

# Simulate inputs from main LM
# The main LM provides:
# - Last layer hidden states
# - First codebook tokens (indices)

lm_hidden_states = torch.randn(batch_size, seq_len, hidden_dim)
first_codebook_tokens = torch.randint(0, 2048, (batch_size, seq_len))

print(f"LM hidden states: {lm_hidden_states.shape}")
print(f"First codebook tokens: {first_codebook_tokens.shape}")

# Look at the embedding structure
print("\n=== Codec Embeddings ===")
codec_embeddings = code_predictor.model.codec_embedding
print(f"Number of embedding layers: {len(codec_embeddings)}")
for i, emb in enumerate(codec_embeddings):
    print(f"  Embedding {i}: {emb}")

# The first embedding is for codebook 0 (first codebook)
# Let's trace through step by step

print("\n=== Step-by-step Generation ===")

with torch.no_grad():
    # Step 1: Prefill with LM hidden states + codebook 0 embeddings
    # The prefill combines:
    # - LM hidden states (projected to code predictor space)
    # - Codebook 0 embeddings

    # Get codebook 0 embeddings
    codebook0_embed = codec_embeddings[0](first_codebook_tokens)
    print(f"Codebook 0 embeddings: {codebook0_embed.shape}")

    # Combine: [hidden_states, codebook0_embed]
    # Wait, let me check the actual input format by looking at forward more carefully

    # From the forward source:
    # - Prefill: inputs_embeds.shape[1] > 1 → generation_steps = seq_len - 2
    # - The input is structured as: [hidden, layer0, ...]

    # Let me try to trace the actual generation
    print("\n=== Tracing Actual Generation ===")

    # For prefill, inputs_embeds should be: [lm_hidden, codebook0_embed]
    # This would give generation_steps = 2 - 2 = 0, which seems wrong

    # Let me look at the talker's code predictor call
    import inspect

    # Find where code_predictor is called in talker
    talker_source = inspect.getsource(type(talker))

    # Search for code_predictor usage
    cp_calls = [line for line in talker_source.split('\n') if 'code_predictor' in line]
    print("Code predictor calls in talker:")
    for call in cp_calls[:20]:
        print(f"  {call.strip()}")

print("\n=== Testing Prefill ===")
# Based on the forward logic:
# - Prefill: inputs_embeds with shape > 1 → generation_steps calculated
# - Input format: [hidden_state, codebook_0_token_embed]
# - generation_steps = seq_len - 2 (hidden & layer 0)

# So for seq_len=10 codec tokens, we'd do:
# Prefill: pass hidden states concat with codebook 0 embeds
# Then decode for codebooks 1-14

with torch.no_grad():
    # Prefill: [lm_hidden, codebook0_embed] concatenated along seq dimension?
    # Or along feature dimension?

    # Looking at the forward:
    # generation_steps = inputs_embeds.shape[1] - 2
    # This suggests the input is [B, N, hidden_dim] where N = 2 (hidden + layer0)

    # Actually, re-reading the forward:
    # - For prefill (inputs_embeds.shape[1] > 1): generation_steps = seq_len - 2
    # - For decode: uses input_ids and embedding[generation_steps-1]

    # I think the prefill input is:
    # inputs_embeds = torch.cat([lm_hidden_states, codebook0_embeds], dim=1)
    # which would have shape [B, seq_len*2, hidden_dim]

    # Let's test this
    prefill_input = torch.cat([lm_hidden_states, codebook0_embed], dim=1)
    print(f"Prefill input shape: {prefill_input.shape}")

    try:
        output = code_predictor(inputs_embeds=prefill_input)
        print(f"Prefill output logits shape: {output.logits.shape}")
        print(f"Generation steps after prefill: {output.generation_steps}")
    except Exception as e:
        print(f"Prefill failed: {e}")
        import traceback
        traceback.print_exc()

print("\n=== Alternative: Single Token Decode ===")
# Try decode mode with a single token
with torch.no_grad():
    try:
        # Decode mode: input_ids + generation_steps
        single_token = first_codebook_tokens[:, :1]  # [B, 1]
        output = code_predictor(input_ids=single_token, generation_steps=1)
        print(f"Decode output logits shape: {output.logits.shape}")
        print(f"Generation steps after decode: {output.generation_steps}")
    except Exception as e:
        print(f"Decode failed: {e}")
        import traceback
        traceback.print_exc()
